### ISSUE TITLE
Supporting Right-to-Left Languages

### ISSUE THREAD

**Issue by forsan** [maximbilan/Language-Manager-iOS#1]
Hi,
First i want to thank you for very good work!
But i have a little problem, Your code work correctly in LTR language but in RTL the storyboard should flip (mirror).
You can find this link to understand what i say exactly.
https://developer.apple.com/library/ios/documentation/MacOSX/Conceptual/BPInternational/SupportingRight-To-LeftLanguages/SupportingRight-To-LeftLanguages.html
So can you help me please!

Note: im using autolayout and when i restart the app and change the language from system to arabic, the view flip correctly.

Many Thanks

**Comment by maximbilan** [comment]
Hi,

I have added arabic language, please check, and say to me is it correct, or something wrong?

**Comment by forsan** [comment]
Hi,
Thanks for update, But you are not got my point.
Please check the images below.
- First image default settings and english language.

![ios simulator screen shot feb 21 2015 6 00 34 pm](https://cloud.githubusercontent.com/assets/1745621/6314547/c2c770da-b9f3-11e4-8590-287b651429c9.png)

Then, I change the default language in simulator to arabic.

![untitled 2](https://cloud.githubusercontent.com/assets/1745621/6314550/cbad4986-b9f3-11e4-95ed-a0cf5050ba15.png)

Check the result now!
Check the position of Hello word and Merry Christmas! Like mirror! this option for RTL Languages.

![ios simulator screen shot feb 21 2015 6 00 57 pm](https://cloud.githubusercontent.com/assets/1745621/6314554/da51f888-b9f3-11e4-930a-1f0fa843f1a7.png)

So, You are not support this feature in you code.
I hope you understand what i want to describe to you.

**Comment by maximbilan** [comment]
Ok, I understood what the problem is. But unfortunately, I don't know how to resolve this. I know that Apple provides AppleTextDirection in NSUserDefaults. Needs time to research.
Thanks.

**Comment by maximbilan** [comment]
I've added some commits for RTL, but the user should restart the application for applying RTL User Interface. For now I could not found the way to reload in the runtime. iOS SDK provides methods only for reading, we can clarify what layout mode is, but we can't set up or reload, unfortunately...

**Comment by forsan** [comment]
Thank you, And i hope you find solution to solve this problem, and i will try to make research also :)
Thanks

**Comment by alirp88** [comment]
#4 @forsan check out the new way to handle RTL to LTR

**Comment by forsan** [comment]
Thanks for great work ;)
