### ISSUE TITLE
Support iOS 11

### ISSUE THREAD

**Issue by keyhan76** [maximbilan/Language-Manager-iOS#17]
Hi,
Please support iOS 11 cause it's a great library.

**Comment by alirp88** [comment]
Hi Keyvan, 

Hope you are doing well, what is your problem with iOS 11? Cause we are already using it and didn’t see any issue.

Thanks

**Comment by keyhan76** [comment]
Hi @alirp88 ,
unfortunately it doesn't support RTL in iOS 11 anymore.
it's working fine with iOS 9 & 10 but in iOS 11 semanticContentAttribute seems to be disabled!
it works only when I restart the application but in iOS 9 & 10 it works just as expected.

**Comment by alirp88** [comment]
This is exactly what we are doing right now, and we are forcing our App to use RTL.

```Objective-C
if ([[[UIView alloc] init] respondsToSelector:@selector(setSemanticContentAttribute:)]) {
   [[UIControl appearance] setSemanticContentAttribute:UISemanticContentAttributeForceRightToLeft];
   [[UIView appearance] setSemanticContentAttribute:UISemanticContentAttributeForceRightToLeft];
   [[UINavigationBar appearance] setSemanticContentAttribute:UISemanticContentAttributeForceRightToLeft];
}
```

Could you show me how are you handling it?

**Comment by keyhan76** [comment]
I’m using this snippet of code that was posted in issue number 6:

Change + (void)setLanguage:(NSString *)language in NSBundle+Language.m to below

+ (void)setLanguage:(NSString *)language
{
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        object_setClass([NSBundle mainBundle], [BundleEx class]);
    });
    if ([LanguageManager isCurrentLanguageRTL]) {
        if ([[[UIView alloc] init] respondsToSelector:@selector(setSemanticContentAttribute:)]) {
            //view
            [[UIView appearance] setSemanticContentAttribute:UISemanticContentAttributeForceRightToLeft];
            //navigation
            [[UINavigationBar appearance] setSemanticContentAttribute:UISemanticContentAttributeForceRightToLeft];
        }
        
        
    }else {
        if ([[[UIView alloc] init] respondsToSelector:@selector(setSemanticContentAttribute:)]) {
            //view
            [[UIView appearance] setSemanticContentAttribute:UISemanticContentAttributeForceLeftToRight];
            //navigation
            [[UINavigationBar appearance] setSemanticContentAttribute:UISemanticContentAttributeForceLeftToRight];
        }
    }
    [[NSUserDefaults standardUserDefaults] setBool:[LanguageManager isCurrentLanguageRTL] forKey:@"AppleTextDirection"];
    [[NSUserDefaults standardUserDefaults] setBool:[LanguageManager isCurrentLanguageRTL] forKey:@"NSForceRightToLeftWritingDirection"];
    [[NSUserDefaults standardUserDefaults] synchronize];
    
    id value = language ? [NSBundle bundleWithPath:[[NSBundle mainBundle] pathForResource:language ofType:@"lproj"]] : nil;
    objc_setAssociatedObject([NSBundle mainBundle], &kBundleKey, value, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
}

**Comment by keyhan76** [comment]
@alirp88,
I tested your code too but still it's not working
