### ISSUE TITLE
Moving To New Project Arabic not supported !!, please i need help

### ISSUE THREAD

**Issue by mrpower55** [maximbilan/Language-Manager-iOS#2]
Hi Guys,

i have try to use this library a lot, example is working well in all languages, but when i try to move files to existing project it is make problems when device is arabic !!.

i can't change the language to base language (english) again.

but when i use existing example it is working fine, so please can anyone help me if there is something should i do to work it well without moving all of my files to existing example !!.

waiting your response.

Best,

**Comment by maximbilan** [comment]
Hi,

Only arabic?
You did everything according to the tutorial?
With using USE_ON_FLY_LOCALIZATION or not?

**Comment by mrpower55** [comment]
yes sure i make eveything like example and i used USE_ON_FLY_LOCALIZATION and i try without it everything working well, but when device is arabic and try to change app lang to english not working.

when i use this example everything working fine.

i guess there is something in build setting ?!!, or in xcode project version !!.

**Comment by maximbilan** [comment]
There are no special settings in xcode project, I don't know what the problem is. Your project with public access?

**Comment by mrpower55** [comment]
ya i know that, jst guessing :(

here is my project if you please can take a look on it.

https://www.dropbox.com/s/023hvk4wxs4cuq2/LanguageChanger.zip?dl=0

**Comment by maximbilan** [comment]
Because your storyboard has not localization file. See the screenshot please. Select a checkmark and the issue will be resolved.

![screen shot 2015-09-10 at 14 36 14](https://cloud.githubusercontent.com/assets/3020089/9787226/9c98ab1c-57c9-11e5-9017-fe5b050a5530.png)

**Comment by mrpower55** [comment]
oooooooooh it is working perfect now, thanks a lot :)

**Comment by maximbilan** [comment]
Not a problem :)
Please 'star' my repository, I will be very grateful.

**Comment by mrpower55** [comment]
sure i ll, u helped me a lot :)
