### ISSUE TITLE
Moving To Another Project Make library Not working unless restart the app !!

### ISSUE THREAD

**Issue by AhmedShammala** [maximbilan/Language-Manager-iOS#8]
[testLanguage.zip](https://github.com/maximbilan/ios_language_manager/files/234190/testLanguage.zip)
Hi Guys ,
First of all your library was working with me Perfect before 
but now it's not that why i guess this happen with Xcode 7 release  ? ,
ur project work Correctly but when Moving To Another Project Make library Not working unless Restart the app .

this my Project you can Try it 
https://www.mediafire.com/?v6le4xcm2qc2k11

PS : I see the isuee #2  and i added the required localization files but still problem exist .
Thanks

**Comment by RajChanchal** [comment]
Same is with me.

**Comment by AhmedShammala** [comment]
@maximbilan  can you please take a look 
Thanks

**Comment by AhmedShammala** [comment]
it's work finally !
Solution is Make  PCH Header on the new project and import inside it  the Define File
import "Defines.h"

**Comment by hardik06** [comment]
This demo is not working in Swift file. I have also created Bridge header to use this demo. 

In LocationManager.m file, there is issue in ` [NSBundle setLanguage:code]; ` executing this line.
See below code :
+ (void)saveLanguageByIndex:(NSInteger)index
{
       if (index >= 0 && index < ELanguageCount)
 {
        NSString *code = LanguageCodes[index];
        [[NSUserDefaults standardUserDefaults] setObject:code forKey:LanguageSaveKey];
        [[NSUserDefaults standardUserDefaults] synchronize];
#ifdef USE_ON_FLY_LOCALIZATION
        [NSBundle setLanguage:code]; //This line isn't executing in Swift. 
#endif
    }
}

Please help me to resolve this issue.

**Comment by AhmedShammala** [comment]
@hardik06  u need to create Prefix Header file and set the path in Project Setting

**Comment by hardik06** [comment]
@AhmedShammala Thank you so much. It's working now.
